baseurl = "https://giodamelio.com/blog/"
languageCode = "en-us"
title = "Gio d'Amelio"
theme = "hyde-x"
paginate = 10
disqusShortname = "giodamelio"

[author]
    name = "Gio d'Amelio"

[permalinks]
    post = "/:year/:month/:day/:title/"

[taxonomies]
    category = "categories"

[params]
    theme = "theme-base-0d"

    # Select a syntax highight.
    # Check the static/css/highlight directory for options.
    highlight = "github"

    # Displays under the author name in the sidebar, keep it short.
    # You can use markdown here.
    tagline = "The Ramblings of a Random Programmer"

    # Text for the top menu link, which goes the root URL for the site.
    # Default (if omitted) is "Blog".
    home = "Blog"

    # Metadata used to drive integrations.
    googleAnalytics = "UA-62281958-2"
    gravatarHash = "cdb3241e99ee754525fc8d976382ad21"

    # Sidebar social links, these must be full URLs.
    github = "https://github.com/giodamelio"
    twitter = "https://twitter.com/GiovannidAmelio"
    bitbucket = ""
    linkedin = ""
    googleplus = ""
    facebook = ""
    youtube = ""

    # Other social-like sidebar links
    rss = true  # switch to true to enable RSS icon link

