backend:
  name: git-gateway
  branch: master
  commit_messages:
    create: 'Create {{collection}} “{{slug}}”'
    update: 'Update {{collection}} “{{slug}}”'
    delete: 'Delete {{collection}} “{{slug}}”'
    uploadMedia: '[skip ci] Upload “{{path}}”'
    deleteMedia: '[skip ci] Delete “{{path}}”'

# Turn on experimental editorial mode
publish_mode: editorial_workflow

# Setup media uploads
media_folder: static/img
public_folder: /img

collections:
  - label: "Pages"
    name: "pages"
    files:
      - label: "Index Page"
        name: "index"
        file: "content/static-page/index.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Body, name: body, widget: markdown}
      - label: "About Page"
        name: "about"
        file: "content/static-page/about.md"
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Name, name: name, widget: string}
          - {label: Path, name: path, widget: string}
          - {label: Order, name: order, widget: number}
          - {label: Body, name: body, widget: markdown}
