name: Publish Site

on:
  push:

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Site
        run: nix run .#zola -- build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  
  publish:
    name: Publish Site
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      id-token: "write"
      pages: "write"
    steps:
      - name: Publish to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

  check-format:
    name: Check Format
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Format
        run: nix flake check

  check-broken-links:
    name: Check for Broken Links
    runs-on: ubuntu-22.04
    needs: publish
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Links
        run: nix run nixpkgs#lychee -- "https://giodamelio.com" "https://giodamelio.com/sitemap.xml" --format=markdown --no-progress --verbose --output="$GITHUB_STEP_SUMMARY"
  
  lighthouse:
    name: Audit Site with Lighthouse
    runs-on: ubuntu-22.04
    needs: publish
    steps:
      - uses: actions/checkout@v4
      - name: Audit URL using Lighthouse
        uses: treosh/lighthouse-ci-action@v12
        id: lighthouse
        with:
          urls: |
            https://giodamelio.com
            https://giodamelio.com/blog/
          uploadArtifacts: true
          temporaryPublicStorage: true
      - name: Display Report
        uses: jackywithawhitedog/lighthouse-viewer-action@v2
        with:
          resultsPath: ${{ steps.lighthouse.outputs.resultsPath }}
          lighthouseOutcome: ${{ steps.lighthouse.outcome }}
  
  wayback-machine:
    name: Save Site to the Wayback Machine
    runs-on: ubuntu-22.04
    needs: publish
    steps:
      - name: Save to Wayback Machine
        uses: JamieMagee/wayback@v2.0.0
        with:
          url: https://giodamelio.com


