name: Publish Site

on:
  push:

jobs:
  build:
    name: Build Site
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Build Site
        run: nix run .#zola -- build
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./public
  
  publish:
    name: Publish Site
    runs-on: ubuntu-22.04
    needs: build
    permissions:
      id-token: "write"
      pages: "read"
    steps:
      - name: Publish to Github Pages
        id: deployment
        uses: actions/deploy-pages@v4

  check-format:
    name: Check Format
    runs-on: ubuntu-22.04
    permissions:
      id-token: "write"
      contents: "read"
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Format
        run: nix flake check

  check-broken-links:
    name: Check for Broken Links
    runs-on: ubuntu-22.04
    needs: publish
    steps:
      - uses: DeterminateSystems/nix-installer-action@main
      - uses: DeterminateSystems/magic-nix-cache-action@main
      - name: Check Links
        run: nix run nixpkgs#lychee "https://giodamelio.com"

